baseURL: "https://followb1ind1y.github.io/"
title: Followb1ind1y
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archives
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Followb1ind1y - https://github.com/Followb1ind1y"
    author: Followb1ind1y
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: "Followb1ind1y's Blog"
        subtitle: "I'm **Zeren**, a Master's student in Mechanical & Industrial Engineering at the **University of Toronto**. I completed my Bachelor's in Statistics and Actuarial Science (Predictive Analytics Specialization) at the **University of Waterloo**. My current research pursuit is Data Science, Deep Learning, Computer Vision, Reinforcement Learning, and Natural Language Processing."
        imageUrl: "/Personal.jpeg"
        #imageTitle: my image
        imageWidth: 300
        imageHeight: 230
        buttons:
            #- name: Resume
            #  url: archives
            #- name: Categories
            #  url: categories

    homeInfoParams:
        Title: "Welcome to Followb1ind1y's Blog"
        Content: >
            - I'm **Zeren**, a Master's student in Mechanical & Industrial Engineering at the **University of Toronto**. I completed my Bachelor's in Statistics and Actuarial Science (Predictive Analytics Specialization) at the **University of Waterloo**. My current research pursuit 🌟 is Data Science, Deep Learning, Computer Vision, Reinforcement Learning, and Natural Language Processing.


    socialIcons:
        - name: github
          url: "https://github.com/Followb1ind1y"
        - name: instagram
          url: "https://www.instagram.com/followblind1y/"
        - name: Facebook
          url: "https://www.facebook.com/zeren.shen"
        - name: Linkedin
          url: "https://www.linkedin.com/in/zeren-shen-566a9119b/"
        - name: WeChat
          url: "/WechatQR.jpeg"
        - name: Email
          url: "mailto:zeren71415@gmail.com"
        - name: Resume
          url: "/Zeren_Resume.pdf"



    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
